### PR TITLE
fix: make upstream optional

### LINKED ISSUE #43: The field 'upstream' should not be required
Currently, it is not possible to apply a Rule without the upstream field being set, this does not reflect what is mentioned in the documentation:

> The location of the server where requests matching this rule should be forwarded to. **This only needs to be set when using the ORY Oathkeeper Proxy as the Decision API does not forward the request to the upstream.**

Error: `The Rule "xyz" is invalid: spec.upstream: Required value`

https://github.com/ory/oathkeeper-maester/blob/master/config/crd/bases/oathkeeper.ory.sh_rules.yaml#L131

### PR DESCRIPTION
**Pull request by m1pl**
fixes #43

### CODE REVIEW

**Comment by m1pl** [comment]
@Demonsthere would this be enough?

**Comment by Demonsthere** [comment]
partially, you still need to regenerate the CRD, by calling `make manifests`, this will update the CRD

**Comment by aeneasr** [comment]
`,omitempty` probably also denotes it as optional?

**Comment by m1pl** [comment]
@Demonsthere done

**Comment by Demonsthere** [comment]
Please run the `make test-integration` suite to verify if all is working as expected :)

**Comment by Demonsthere** [comment]
`,omitempty` allows the json schema to accept an empty parameter as `upstream`, so that a json without this field is properly parsed. So yeah, if we want to make the field optional, need to add it

**Comment by Demonsthere** [comment]
Those are the [tests](https://github.com/ory/oathkeeper-maester/blob/master/api/v1alpha1/rule_types_test.go) we need to update to make sure rules with or without upstream fields are accepted

**Comment by m1pl** [comment]
```
Ran 1 of 1 Specs in 65.149 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
```

**Comment by Demonsthere** [comment]
My followup with expanded tests, stil wip https://github.com/ory/oathkeeper-maester/pull/47

**Comment by aeneasr** [comment]
So should we close this if you work on #47?

**Comment by Demonsthere** [comment]
Yes, #47 is based on this, and only adds tests to verify if it works. We can merge #47 and then close this and #43

**Pull request closed without merging**
